# Facts are discovered by Ansible and in xsce-facts.yml which also computes networking values to use

- name: Create xs network flags
  template: backup=yes
            src={{ item }}.j2
            dest=/etc/sysconfig/{{ item }}
            mode=0644
  with_items:
    - xs_wan_device
    - xs_lan_device
    - xs_domain_name
  tags:
    - network-discover


- name: Configure /etc/sysconfig/network
  template: backup=yes
            src=sysconfig.network.j2
            dest=/etc/sysconfig/network
            owner=root
            group=root
            mode=0644

- name: Configure /etc/hosts
  template: src=hosts.j2
            dest=/etc/hosts
            owner=root
            group=root
            mode=0644            

- name: Configure lan interface
  template: backup=yes
            src=ifcfg.j2
            dest=/etc/sysconfig/network-scripts/ifcfg-{{xsce_lan_iface}}
  when: 'xsce_lan_iface != "" '

- include: named.yml
  tags:
    - named
    - network
